using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Support.UI;
using System;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;

class Program
{
    static void Main()
    {
        string url = "https://app.cloudqa.io/home/AutomationPracticeForm";

        IWebDriver driver = new ChromeDriver();
        driver.Navigate().GoToUrl(url);
        driver.Manage().Window.Maximize();



        IWebElement FindInputByPlaceholder(string placeholderText)
        {
            return driver.FindElements(By.XPath($"//input[@placeholder='{placeholderText}']")).FirstOrDefault();
        }

        IWebElement FindInputByLabel(string labelText)
        {
            var xpath = $"//*[normalize-space(text())='{labelText}']//following::input[1] | " +
                        $"//*[normalize-space(text())='{labelText}']//following::textarea[1] | " +
                        $"//*[normalize-space(text())='{labelText}']//following::select[1]";

            return driver.FindElements(By.XPath(xpath)).FirstOrDefault();
        }

        void SafeClick(IWebElement el)
        {
            try { el?.Click(); } catch { }
        }

        void SafeSendKeys(IWebElement el, string text)
        {
            try { if (el != null) { el.Clear(); el.SendKeys(text); } } catch { }
        }

        void SelectStateCountry()
        {
            try
            {
                var stateSelect = driver.FindElement(By.XPath("//select[@id='state']"));
                var sel = new SelectElement(stateSelect);
                sel.SelectByText("India");
                Console.WriteLine("✓ State set to India");
            }
            catch (Exception ex)
            {
                Console.WriteLine("State dropdown error: " + ex.Message);
            }
        }


        void FillFields()
        {
            try
            {

                SafeSendKeys(FindInputByLabel("First Name"), "Divya");
                SafeSendKeys(FindInputByLabel("Last Name"), "Chaudhary");
                SafeSendKeys(FindInputByLabel("Email"), "divyachaudhary@gmail.com");
                SafeSendKeys(FindInputByLabel("Mobile #"), "9876543210");
                SafeSendKeys(FindInputByLabel("Date of Birth"), "2006-03-31");
                SafeSendKeys(FindInputByLabel("Country"), "India");

                SafeSendKeys(FindInputByPlaceholder("Username"), "divya1388");
                SafeSendKeys(FindInputByPlaceholder("Password"), "Divya@123");
                SafeSendKeys(FindInputByPlaceholder("Confirm Password"), "Divya@123");





                var descriptionBox = driver.FindElements(By.TagName("textarea"))
                                           .FirstOrDefault(t => t.Displayed);

                if (descriptionBox != null)
                {
                    descriptionBox.Clear();

                    string text =
                        "Hello! This is an autogenerated text! nice to meet you. Hire Me.";

                    descriptionBox.SendKeys(text);
                }



                var radioGroups = driver.FindElements(By.XPath("//input[@type='radio']")); if (radioGroups.Any())
                {
                    try
                    {
                        var maleLabel = driver.FindElements(By.XPath("//label[normalize-space(.)='Female' or normalize-space(.)='female']")).FirstOrDefault(); if (maleLabel != null) SafeClick(maleLabel); else { var anyRadio = radioGroups.FirstOrDefault(r => r.Enabled && r.Displayed); if (anyRadio != null) SafeClick(anyRadio); }
                    }
                    catch { }
                }
                var checkboxes = driver.FindElements(By.XPath("//input[@type='checkbox']")); int cbCount = 0; foreach (var cb in checkboxes) { try { if (cb.Displayed && cb.Enabled && !cb.Selected) { cb.Click(); cbCount++; if (cbCount >= 2) break; } } catch { } }






            }
            catch { }
        }








        var fileInputs = driver.FindElements(By.XPath("//input[@type='file']")); foreach (var fi in fileInputs) { try { fi.SendKeys(@"C:\Users\divya\Downloads\Divya-Chaudhary-FlowCV-Resume-20251126.pdf"); } catch { } }


        void ProcessFramesNoID()
        {
            FillFields();
            SelectStateCountry();

            var fileInputs = driver.FindElements(By.XPath("//input[@type='file']")); foreach (var fi in fileInputs) { try { fi.SendKeys(@"C:\Users\divya\Downloads\Divya-Chaudhary-FlowCV-Resume-20251126.pdf"); } catch { } }
            var frames = driver.FindElements(By.XPath("//iframe[not(@id)]"));

            foreach (var frame in frames)
            {
                try
                {
                    driver.SwitchTo().Frame(frame);
                    ProcessFramesNoID();
                    driver.SwitchTo().ParentFrame();
                }
                catch
                {
                    driver.SwitchTo().DefaultContent();
                }
            }
        }



        ProcessFramesNoID();

        Console.WriteLine("Done. Press ENTER to exit.");
        Console.ReadLine();
        driver.Quit();
    }
}
